use_frameworks!

platform :ios, '8.0'

target 'TGNews_Example' do
  pod 'TGNews', :path => '../'

  target 'TGNews_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
